# Generated by Django 5.0.6 on 2024-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, default='https://res.cloudinary.com/dchytnqhl/image/upload/v1723662781/fakeverse/default.png', max_length=255, null=True),
        ),
    ]
